# Generated by Django 5.2.12 on 2026-04-23 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=100, verbose_name='Nome do doador')),
                ('donor_email', models.EmailField(max_length=254, verbose_name='E-mail do doador')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor (R$)')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado')], default='pending', max_length=20, verbose_name='Status')),
                ('payment_method', models.CharField(blank=True, choices=[('pix', 'PIX'), ('credit_card', 'Cartão de Crédito'), ('boleto', 'Boleto')], max_length=20, verbose_name='Método de pagamento')),
                ('message', models.TextField(blank=True, verbose_name='Mensagem para o criador')),
                ('anonymous', models.BooleanField(default=False, verbose_name='Doação anônima')),
                ('mp_preference_id', models.CharField(blank=True, max_length=200)),
                ('mp_payment_id', models.CharField(blank=True, max_length=100)),
                ('mp_external_reference', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='campaigns.campaign', verbose_name='Campanha')),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to=settings.AUTH_USER_MODEL, verbose_name='Doador (conta)')),
            ],
            options={
                'verbose_name': 'Doação',
                'verbose_name_plural': 'Doações',
                'ordering': ['-created_at'],
            },
        ),
    ]
