# Generated by Django 5.2.12 on 2026-04-23 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(verbose_name='Descrição')),
                ('goal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Meta (R$)')),
                ('raised', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Arrecadado (R$)')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('active', 'Ativa'), ('completed', 'Concluída'), ('cancelled', 'Cancelada')], default='draft', max_length=20, verbose_name='Status')),
                ('image', models.ImageField(blank=True, null=True, upload_to='campaigns/', verbose_name='Imagem')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Prazo')),
                ('beneficiary', models.CharField(blank=True, max_length=200, verbose_name='Beneficiário')),
                ('fund_usage', models.TextField(blank=True, verbose_name='Como o dinheiro será usado')),
                ('campaign_reason', models.TextField(blank=True, verbose_name='Motivo da campanha')),
                ('created_via_whatsapp', models.BooleanField(default=False)),
                ('whatsapp_jid', models.CharField(blank=True, max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL, verbose_name='Criador')),
            ],
            options={
                'verbose_name': 'Campanha',
                'verbose_name_plural': 'Campanhas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Atualização')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='campaigns.campaign', verbose_name='Campanha')),
            ],
            options={
                'verbose_name': 'Atualização',
                'verbose_name_plural': 'Atualizações',
                'ordering': ['-created_at'],
            },
        ),
    ]
