# Generated by Django 5.2.12 on 2026-04-28 17:35

import django.db.models.deletion
from django.db import migrations, models


def seed_categories(apps, schema_editor):
    Category = apps.get_model("campaigns", "Category")
    defaults = [
        (0, "Saúde", "saude"),
        (10, "Educação", "educacao"),
        (20, "Animais", "animais"),
        (30, "Emergência", "emergencia"),
        (40, "Comunidade", "comunidade"),
        (50, "Arte e cultura", "arte-cultura"),
        (60, "Memorial / luto", "memorial"),
        (100, "Outros", "outros"),
    ]
    for ordering, name, slug in defaults:
        Category.objects.get_or_create(
            slug=slug, defaults={"name": name, "ordering": ordering}
        )


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=96, unique=True)),
                ('ordering', models.PositiveSmallIntegerField(db_index=True, default=0)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['ordering', 'name'],
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='campaigns.category', verbose_name='Categoria'),
        ),
        migrations.RunPython(seed_categories, migrations.RunPython.noop),
    ]
